# Generated by Django 3.0.3 on 2020-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='team',
            field=models.CharField(choices=[('none', 'NBA'), ('hawks', 'Atlanta Hawks'), ('celtics', 'Boston Celtics'), ('nets', 'Brooklyn Nets'), ('hornets', 'Charlotte Hornets'), ('bulls', 'Chicago Bulls'), ('cavaliers', 'Cleveland Cavaliers'), ('mavericks', 'Dallas Mavericks'), ('nuggets', 'Denver Nuggets'), ('pistons', 'Denver Pistons'), ('warriors', 'Golden State Warriors'), ('rockets', 'Houston Rockets'), ('pacers', 'Indiana Pacers'), ('clippers', 'Los Angeles Clippers'), ('lakers', 'Los Angeles Lakers')], default='none', max_length=32),
        ),
    ]
