# Generated by Django 3.0.4 on 2020-04-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='slug',
            field=models.SlugField(default='slug_default', unique=True),
            preserve_default=False,
        ),
    ]
