# Generated by Django 3.0.5 on 2020-04-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nba_games', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(default='null-channel', max_length=225),
            preserve_default=False,
        ),
    ]
